-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 22:42:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema job_fair_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema job_fair_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `job_fair_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `job_fair_db` ;

-- -----------------------------------------------------
-- Table `job_fair_db`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_fair_db`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_description` TEXT NULL DEFAULT NULL,
  `company_name` VARCHAR(100) NOT NULL,
  `company_location` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `job_fair_db`.`job_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_fair_db`.`job_posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `job_title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `required_skills` TEXT NULL DEFAULT NULL,
  `salary_range` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `job_posts_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `job_fair_db`.`employees` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `job_fair_db`.`job_seekers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_fair_db`.`job_seekers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cv` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `contact_no` VARCHAR(15) NULL DEFAULT NULL,
  `created_At` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_At` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `job_fair_db`.`applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_fair_db`.`applications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_post_id` INT NOT NULL,
  `job_seeker_id` INT NOT NULL,
  `status` ENUM('approved', 'rejected', 'hired') NOT NULL,
  `submitted_At` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `job_post_id` (`job_post_id` ASC) VISIBLE,
  INDEX `job_seeker_id` (`job_seeker_id` ASC) VISIBLE,
  CONSTRAINT `applications_ibfk_1`
    FOREIGN KEY (`job_post_id`)
    REFERENCES `job_fair_db`.`job_posts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `applications_ibfk_2`
    FOREIGN KEY (`job_seeker_id`)
    REFERENCES `job_fair_db`.`job_seekers` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `job_fair_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job_fair_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'employer', 'job_seeker') NOT NULL,
  `created_At` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_At` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
